### ISSUE TITLE
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by sepehrvakili** [marudor/libxmljs2#170]
Seeing this error, any suggestion for a fix or workaround?
Using node 14.16.1.

```
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found 
(required by /home/project/node_modules/libxmljs2/build/Release/xmljs.node)
```

**Comment by vagdwd** [comment]
Facing the exact same issue on node 16.13.1

**Comment by marudor** [comment]
Looks like an old libsttdc version on your side that does not support CXXABI_1.3.9 yet.

**Comment by sharq88** [comment]
**How to fix "/usr/lib64/libstdc++.so.6: version `CXXABI_1.3.X' not found"**
The root cause is your local GCC is outdated. You haven't stated what your base OS is, so I drop here some instructions which worked for me on an outdated CentOS 7 https://github.com/Automattic/node-canvas/issues/1796#issuecomment-921823147 It probably wont be a copy paste solution for you, but it can help going in the right direction to fix it.
